version: "1.0"
services:
  webApi:    
    container_name: webApi
    build:      
      context: ..
      dockerfile: ./ECommece/ECommece.Web.API/Dockerfile
    depends_on: [ mssql ]        
    ports:
      - "8080:80"
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssql
    hostname: mssql
    environment:
      SA_PASSWORD: "En3s@123!"
      ACCEPT_EULA: "Y"
    restart: unless-stopped    
    ports:
      - "11433:1433"